insert into collections (`id`, `name`, `description`, `path`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(1, 'Summer 2010', 'Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse, viverra dolor accumsan quis praesent sit. Ac fugit in vivamus. Rhoncus libero fringilla. Per tempus morbi luctus in vehicula, ut mi egestas massa laoreet.', 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1', 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7923_thumb.jpg', 260, 173);

insert into images (`id`, `name`, `description`, `collection_id`, `path`, `width`, `height`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(1, 'Collection 1 - Photo 1', 'Photo 1 description: Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse', 1, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7923.jpg', 600, 400, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7923_thumb.jpg', 260, 173);
insert into images (`id`, `name`, `description`, `collection_id`, `path`, `width`, `height`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(2, 'Collection 1 - Photo 2', 'Photo 2 description: Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse', 1, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7924.jpg', 400, 600, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7924_thumb.jpg', 173, 260);
insert into images (`id`, `name`, `description`, `collection_id`, `path`, `width`, `height`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(3, 'Collection 1 - Photo 3', 'Photo 3 description: Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse', 1, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7930.jpg', 600, 400, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7930_thumb.jpg', 260, 173);
insert into images (`id`, `name`, `description`, `collection_id`, `path`, `width`, `height`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(4, 'Collection 1 - Photo 4', 'Photo 4 description: Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse', 1, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7941.jpg', 400, 600, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7941_thumb.jpg', 173, 260);
insert into images (`id`, `name`, `description`, `collection_id`, `path`, `width`, `height`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(5, 'Collection 1 - Photo 5', 'Photo 5 description: Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse', 1, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7955.jpg', 600, 400, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7955_thumb.jpg', 260, 173);
insert into images (`id`, `name`, `description`, `collection_id`, `path`, `width`, `height`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(6, 'Collection 1 - Photo 6', 'Photo 6 description: Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse', 1, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7961.jpg', 600, 400, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7961_thumb.jpg', 260, 173);
insert into images (`id`, `name`, `description`, `collection_id`, `path`, `width`, `height`, `thumbnail_path`, `thumbnail_width`, `thumbnail_height`) values(7, 'Collection 1 - Photo 7', 'Photo 7 description: Lorem ipsum dolor sit amet, in diam nisl ut tellus a in, in vestibulum ante ante sed, interdum ornare ut, arcu posuere vehicula suspendisse', 1, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7968.jpg', 600, 400, 'http://138634981.rm1.cloudaccess.it/dimitri_photocloud/collection_1/IMG_7968_thumb.jpg', 260, 173);
